{{- if .Values.acceptance-test.certificate.create -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "podinfo.fullname" . }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
spec:
  dnsNames:
  {{- range .Values.acceptance-test.certificate.dnsNames }}
    - {{ . | quote }}
  {{- end }}
  secretName: {{ template "podinfo.tlsSecretName" . }}
  issuerRef:
  {{- .Values.acceptance-test.certificate.issuerRef | toYaml | trimSuffix "\n" | nindent 4 }}
{{- end }}
