{{- if .Values.acceptance-test.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "podinfo.fullname" . }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "podinfo.fullname" . }}
  minReplicas: {{ .Values.acceptance-test.replicaCount }}
  maxReplicas: {{ .Values.acceptance-test.hpa.maxReplicas }}
  metrics:
  {{- if .Values.acceptance-test.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.acceptance-test.hpa.cpu }}
  {{- end }}
  {{- if .Values.acceptance-test.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.acceptance-test.hpa.memory }}
  {{- end }}
  {{- if .Values.acceptance-test.hpa.requests }}
  - type: Pods
    pods:
      metric:
        name: http_requests
      target:
        type: AverageValue
        averageValue: {{ .Values.acceptance-test.hpa.requests }}
  {{- end }}
{{- end }}
